### ISSUE TITLE
viking Roadmap

### ISSUE THREAD

**Issue by thehedhly** [d3witt/viking#10]
Hey @d3witt, thank you for this owesome tool!
imo it it has the potential to be an ansible GO written alternative in the long run, what is your opinion about that?

**Comment by d3witt** [comment]
Hey, thanks! Viking will handle basic tasks for managing multiple machines, similar to Ansible. However, there are currently no plans to build something like playbooks. Instead, Viking will focus on a Docker/containers-centric approach.
