### ISSUE TITLE
Ability to set custom port on machine

### ISSUE THREAD

**Issue by greyhoundforty** [d3witt/viking#6]
Currently there is no way to set a custom port for a machine. I also attempted to add it after the IP using the `:` notation but it also failed:

```
% viking machine add --name sh1-0151 --user ryan --key andromeda --port 3322 192.168.86.41
Incorrect Usage: flag provided but not defined: -port

% viking machine add --name sh1-0151 --user ryan --key andromeda 192.168.86.41:3322
Error: host must be valid ip address
```

**Comment by d3witt** [comment]
Now you can specify port via —port (-p) flag or put it in host like `192.168.86.41:3322`
