### ISSUE TITLE
Error to get PRIVATE KEY from powershell

### ISSUE THREAD

**Issue by lfelipe1501** [d3witt/viking#9]
When I run the command to get the private key in powershell it is not correctly mapping the private flag to get it.

![image](https://github.com/user-attachments/assets/0a957392-aba1-402e-9f04-7ecc9db45e91)

**Comment by d3witt** [comment]
The `--private flag` is gone. It’s a documentation error. You can still grab the private key manually from the config file (`viking config`). What’s the use case? Why do you need to copy the private key?
